# Generated by Django 3.0.4 on 2020-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
