# Generated by Django 3.0.4 on 2020-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_ammount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ammount',
        ),
        migrations.AddField(
            model_name='orders',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
